nelmio_cors:
  defaults:
#    origin_regex: true
#    allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    allow_origin: ['http://localhost:5173', 'http://192.168.1.8:5173', '*']
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ 'Content-Type', 'Authorization' ]
    expose_headers: [ 'Link' ]
    max_age: 3600
  paths:
    '^/api/':
#      origin_regex: true
#      allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
      allow_origin: ['*']
      allow_headers: [ '*' ]
      allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
      max_age: 3600
